apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: postgresql-rds
  annotations:
    guide: quickstart
    provider: aws
    vpc: default
spec:
  crossplane:
    version: ">=v1.4.0-0"
  dependsOn:
    - provider: crossplane/provider-aws
      version: ">=v0.18.2"
