apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-creds
      key: creds
---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: aws-rds-posgresql
spec:
  ignoreCrossplaneConstraints: false
  package: driosalido/postgresql-rds-aws:v0.0.1
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 0
  skipDependencyResolution: false
