apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  finalizers:
    - in-use.crossplane.io  
spec:
  credentials:
    secretRef:
      key: creds
      name: aws-creds
      namespace: crossplane-system
    source: Secret
